import {
	siAnthropic,
	siApple,
	siApplemusic,
	siAppstore,
	siArxiv,
	siAtlassian,
	siBandcamp,
	siBehance,
	siBluesky,
	siBookingdotcom,
	siClaude,
	siCloudflare,
	siCodesandbox,
	siDevdotto,
	siDiscord,
	siDocker,
	siDribbble,
	siDropbox,
	siDuolingo,
	siEbay,
	siEtsy,
	siFacebook,
	siFigma,
	siGithub,
	siGitlab,
	siGmail,
	siGoodreads,
	siGoogle,
	siGooglecalendar,
	siGoogledocs,
	siGoogledrive,
	siGooglemaps,
	siGoogleplay,
	siGooglescholar,
	siGooglesheets,
	siGoogleslides,
	siHuggingface,
	siImdb,
	siInstagram,
	siItchdotio,
	siKaggle,
	siKofi,
	siLeetcode,
	siLetterboxd,
	siMastodon,
	siMdnwebdocs,
	siMedium,
	siNetflix,
	siNotion,
	siNpm,
	siObsidian,
	siPatreon,
	siPaypal,
	siPinterest,
	siProducthunt,
	siProtonmail,
	siPypi,
	siQuora,
	siReddit,
	siSignal,
	siSoundcloud,
	siSpotify,
	siStackblitz,
	siStackoverflow,
	siSteam,
	siSubstack,
	siSvelte,
	siTelegram,
	siThreads,
	siTiktok,
	siTrello,
	siTumblr,
	siTwitch,
	siVercel,
	siVimeo,
	siWhatsapp,
	siWikipedia,
	siWordpress,
	siX,
	siYcombinator,
	siYoutube,
	siYoutubemusic,
	siZoom,
	type SimpleIcon
} from 'simple-icons';

// Bundled brand glyphs, so a link shows its site's mark without the browser
// contacting that site (or anyone else) to fetch a favicon.
const ICONS: Record<string, SimpleIcon> = {
	'anthropic.com': siAnthropic,
	'apple.com': siApple,
	'music.apple.com': siApplemusic,
	'apps.apple.com': siAppstore,
	'arxiv.org': siArxiv,
	'atlassian.net': siAtlassian,
	'atlassian.com': siAtlassian,
	'bandcamp.com': siBandcamp,
	'behance.net': siBehance,
	'bsky.app': siBluesky,
	'booking.com': siBookingdotcom,
	'claude.ai': siClaude,
	'cloudflare.com': siCloudflare,
	'codesandbox.io': siCodesandbox,
	'dev.to': siDevdotto,
	'discord.com': siDiscord,
	'discord.gg': siDiscord,
	'docker.com': siDocker,
	'dribbble.com': siDribbble,
	'dropbox.com': siDropbox,
	'duolingo.com': siDuolingo,
	'ebay.com': siEbay,
	'etsy.com': siEtsy,
	'facebook.com': siFacebook,
	'fb.com': siFacebook,
	'figma.com': siFigma,
	'github.com': siGithub,
	'github.io': siGithub,
	'gitlab.com': siGitlab,
	'mail.google.com': siGmail,
	'goodreads.com': siGoodreads,
	'google.com': siGoogle,
	'calendar.google.com': siGooglecalendar,
	'docs.google.com': siGoogledocs,
	'drive.google.com': siGoogledrive,
	'maps.google.com': siGooglemaps,
	'maps.app.goo.gl': siGooglemaps,
	'play.google.com': siGoogleplay,
	'scholar.google.com': siGooglescholar,
	'sheets.google.com': siGooglesheets,
	'slides.google.com': siGoogleslides,
	'huggingface.co': siHuggingface,
	'imdb.com': siImdb,
	'instagram.com': siInstagram,
	'itch.io': siItchdotio,
	'kaggle.com': siKaggle,
	'ko-fi.com': siKofi,
	'leetcode.com': siLeetcode,
	'letterboxd.com': siLetterboxd,
	'mastodon.social': siMastodon,
	'developer.mozilla.org': siMdnwebdocs,
	'medium.com': siMedium,
	'netflix.com': siNetflix,
	'notion.so': siNotion,
	'notion.site': siNotion,
	'npmjs.com': siNpm,
	'obsidian.md': siObsidian,
	'patreon.com': siPatreon,
	'paypal.com': siPaypal,
	'pinterest.com': siPinterest,
	'pin.it': siPinterest,
	'producthunt.com': siProducthunt,
	'proton.me': siProtonmail,
	'pypi.org': siPypi,
	'quora.com': siQuora,
	'reddit.com': siReddit,
	'redd.it': siReddit,
	'signal.org': siSignal,
	'soundcloud.com': siSoundcloud,
	'spotify.com': siSpotify,
	'stackblitz.com': siStackblitz,
	'stackoverflow.com': siStackoverflow,
	'steampowered.com': siSteam,
	'steamcommunity.com': siSteam,
	'substack.com': siSubstack,
	'svelte.dev': siSvelte,
	't.me': siTelegram,
	'telegram.org': siTelegram,
	'threads.net': siThreads,
	'tiktok.com': siTiktok,
	'trello.com': siTrello,
	'tumblr.com': siTumblr,
	'twitch.tv': siTwitch,
	'vercel.app': siVercel,
	'vercel.com': siVercel,
	'vimeo.com': siVimeo,
	'whatsapp.com': siWhatsapp,
	'wa.me': siWhatsapp,
	'wikipedia.org': siWikipedia,
	'wordpress.com': siWordpress,
	'x.com': siX,
	'twitter.com': siX,
	'news.ycombinator.com': siYcombinator,
	'youtube.com': siYoutube,
	'youtu.be': siYoutube,
	'music.youtube.com': siYoutubemusic,
	'zoom.us': siZoom
};

/** The bundled brand glyph for a hostname or its closest listed parent domain. */
export function siteIcon(hostname: string): SimpleIcon | undefined {
	const labels = hostname.toLowerCase().split('.');
	for (let i = 0; i < labels.length - 1; i++) {
		const icon = ICONS[labels.slice(i).join('.')];
		if (icon) return icon;
	}
	return undefined;
}
