version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      weekly-batch:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      weekly-batch:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      weekly-batch:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
