// Server-side opaque sync storage. The server authenticates accounts but never receives
// notes, labels, images, tombstones, or any decryptable user payload.
import type { Client, InStatement, Transaction } from '@libsql/client/web';
import { env } from '$env/dynamic/private';
import {
	ACTIVITY_WINDOWS_DAYS,
	DEFAULT_HISTORY_VERSIONS,
	DEFAULT_MAX_ACCOUNT_BYTES,
	DEFAULT_SYNC_PER_MINUTE,
	parseHistoryVersions,
	parseMaxAccountBytes
} from '$lib/server/operatorConfig';
import { getDb, withTxn, type Db } from '$lib/server/db';
import { syncEventEmitter } from '$lib/server/syncEvents';
import type { HistoryEnvelope, HistoryList } from '$lib/syncHistory';

/** `slot` is an opaque, keyed identifier generated by the client for a logical record.
 * It lets the relay replace an old ciphertext without learning whether it is a note, image, etc. */
export type EncryptedEnvelope = { seq: number; id: string; ciphertext: string; slot: string };
export type OpaqueUpload = Omit<EncryptedEnvelope, 'seq'> & {
	expectedId?: string | null;
	/** The upload continues the version it replaces, which then leaves the history. */
	continues?: boolean;
};
export type OpaqueDelete = { id: string; slot: string };

export type SyncResult = {
	cursor: number;
	envelopes: EncryptedEnvelope[];
	conflicts: EncryptedEnvelope[];
	hasMore: boolean;
	reset: boolean;
	writesAccepted: boolean;
};

export type SyncStoreOptions = {
	maxAccountBytes?: number;
	historyVersions?: number;
};

type AccountRow = {
	nextSeq: number;
	envelopeCount: number;
	ciphertextBytes: number;
};

export type AccountByteQuota = {
	maxBytes: number;
	overridden: boolean;
};

type UsageRow = {
	envelopeCount: number;
	ciphertextBytes: number;
	storageBytes: number;
};

export type SyncQuotas = {
	maxAccountBytes: number;
};

export type OperatorUsage = UsageRow & {
	accounts: number;
	activeByWindowDays: Record<string, number>;
	staleAccounts: number;
};

/** Conservative allowance for row, key, and index storage beyond the ciphertext itself. */
export const ENVELOPE_STORAGE_OVERHEAD_BYTES = 512;
export const MAX_PUSH_DEVICES = 32;
export const MAX_WAKES_PER_ACCOUNT = 1_000;
export const WAKE_RETAIN_MS = 24 * 60 * 60 * 1000;
export const WAKE_CLAIM_LEASE_MS = 60_000;
export const MAX_SYNC_MUTATIONS_PER_REQUEST = 2_000;
/** Bound for IN (...) lists so sweeps stay under the SQLite host-parameter limit. */
const ACCOUNT_CHUNK = 400;

export type PushDeviceInput = {
	deviceId: string;
	endpoint: string;
	p256dh: string;
	auth: string;
	accountId: string;
};

export type DueWake = {
	accountId: string;
	deviceId: string;
	wakeId: string;
	fireAt: number;
	endpoint: string;
	p256dh: string;
	auth: string;
};

export type ReminderWakeInput = { id: string; fireAt: number };

/** ASCII-only ciphertext keeps JS `.length` equal to SQLite `length()` for quota math. */
const BASE64URL = /^[A-Za-z0-9_-]+$/;

export type AccountSummary = {
	accountId: string;
	envelopeCount: number;
	ciphertextBytes: number;
	storageBytes: number;
	lastSeenAt: number;
	maxBytes: number;
	maxBytesOverridden: boolean;
	syncPerMinute: number;
	syncPerMinuteOverridden: boolean;
};

export type AccountPage = { total: number; accounts: AccountSummary[] };

export class SyncQuotaExceededError extends Error {
	constructor() {
		super('Sync account storage quota exceeded');
		this.name = 'SyncQuotaExceededError';
	}
}

function chunk<T>(values: T[]): T[][] {
	const chunks: T[][] = [];
	for (let offset = 0; offset < values.length; offset += ACCOUNT_CHUNK) {
		chunks.push(values.slice(offset, offset + ACCOUNT_CHUNK));
	}
	return chunks;
}

async function executeInBatches(tx: Transaction, statements: InStatement[]): Promise<void> {
	for (const batch of chunk(statements)) await tx.batch(batch);
}

/**
 * A history row counted in quota: an older version of a record that still exists. The live
 * copy each record's history holds is already counted.
 */
const OLDER_VERSION = `EXISTS (
	SELECT 1 FROM envelopes AS live
	WHERE live.account_id = history.account_id AND live.slot = history.slot AND live.id != history.id
)`;

/** Count and bytes of the older versions the given records hold. */
async function olderVersions(
	tx: Transaction,
	accountId: string,
	slots: string[]
): Promise<{ versions: number; bytes: number }> {
	let versions = 0;
	let bytes = 0;
	for (const slotBatch of chunk(slots)) {
		const row = (
			await tx.execute({
				sql: `SELECT COUNT(*) AS versions, COALESCE(SUM(length(ciphertext)), 0) AS bytes
				FROM envelope_history AS history
				WHERE account_id = ? AND slot IN (${slotBatch.map(() => '?').join(', ')}) AND ${OLDER_VERSION}`,
				args: [accountId, ...slotBatch]
			})
		).rows[0] as unknown as { versions: number; bytes: number };
		versions += Number(row.versions);
		bytes += Number(row.bytes);
	}
	return { versions, bytes };
}

export class SyncStore {
	private readonly db: Db;
	private readonly maxAccountBytes: number;
	private readonly historyVersions: number;

	constructor(db: Db, options: SyncStoreOptions = {}) {
		this.db = db;
		this.maxAccountBytes = options.maxAccountBytes ?? DEFAULT_MAX_ACCOUNT_BYTES;
		this.historyVersions = options.historyVersions ?? DEFAULT_HISTORY_VERSIONS;
	}

	private get relay(): Client {
		return this.db.relay;
	}

	private get ops(): Client {
		return this.db.ops;
	}

	/** A record's retained encrypted versions, newest first. */
	async listHistory(accountId: string, slot: string): Promise<HistoryList> {
		await this.db.ready;
		const versions = (
			await this.relay.execute({
				sql: `SELECT history_id AS historyId, saved_at AS savedAt, id, ciphertext FROM envelope_history
				WHERE account_id = ? AND slot = ? ORDER BY history_id DESC LIMIT ?`,
				args: [accountId, slot, this.historyVersions]
			})
		).rows as unknown as HistoryList['versions'];
		return { versions };
	}

	/** The first version of a record saved at or after `at`, else the live one. */
	async getEnvelopeAt(
		accountId: string,
		slot: string,
		at: number
	): Promise<HistoryEnvelope | null> {
		await this.db.ready;
		const historical = (
			await this.relay.execute({
				sql: `SELECT id, slot, ciphertext FROM envelope_history
				WHERE account_id = ? AND slot = ? AND saved_at >= ?
				ORDER BY saved_at ASC, history_id ASC LIMIT 1`,
				args: [accountId, slot, at]
			})
		).rows[0] as unknown as HistoryEnvelope | undefined;
		if (historical) return historical;
		const current = (
			await this.relay.execute({
				sql: 'SELECT id, slot, ciphertext FROM envelopes WHERE account_id = ? AND slot = ?',
				args: [accountId, slot]
			})
		).rows[0] as unknown as HistoryEnvelope | undefined;
		return current ?? null;
	}

	async getAuthCredential(accountId: string): Promise<string | null> {
		await this.db.ready;
		const result = await this.relay.execute({
			sql: 'SELECT credential_hash AS credentialHash FROM accounts WHERE account_id = ?',
			args: [accountId]
		});
		return (
			(result.rows[0] as unknown as { credentialHash: string } | undefined)?.credentialHash ?? null
		);
	}

	async replaceAuthCredential(
		accountId: string,
		expected: string,
		replacement: string
	): Promise<boolean> {
		await this.db.ready;
		const result = await this.relay.execute({
			sql: 'UPDATE accounts SET credential_hash = ?, updated_at = ? WHERE account_id = ? AND credential_hash = ?',
			args: [replacement, Date.now(), accountId, expected]
		});
		return result.rowsAffected === 1;
	}

	async createAccount(
		accountId: string,
		authPublicKey: string,
		updatedAt = Date.now()
	): Promise<boolean> {
		await this.db.ready;
		const result = await this.relay.execute({
			sql: `
			INSERT OR IGNORE INTO accounts(
				account_id, credential_hash, next_seq, envelope_count, ciphertext_bytes, updated_at, last_seen_at
			)
			SELECT ?, ?, 0, 0, 0, ?, ?
			WHERE NOT EXISTS (SELECT 1 FROM retired_accounts WHERE account_id = ?)
		`,
			args: [accountId, authPublicKey, updatedAt, updatedAt, accountId]
		});
		return result.rowsAffected === 1;
	}

	/** Refuse this account id from now on. Recorded before the account is deleted,
	 * so no registration can slip in between the two. */
	async retireAccount(accountId: string, now = Date.now()): Promise<void> {
		await this.db.ready;
		await this.relay.execute({
			sql: 'INSERT OR IGNORE INTO retired_accounts(account_id, retired_at) VALUES (?, ?)',
			args: [accountId, now]
		});
	}

	async isAccountRetired(accountId: string): Promise<boolean> {
		await this.db.ready;
		const result = await this.relay.execute({
			sql: 'SELECT 1 FROM retired_accounts WHERE account_id = ?',
			args: [accountId]
		});
		return result.rows.length > 0;
	}

	async getAccountByteQuota(
		accountId: string,
		defaultMaxAccountBytes = this.maxAccountBytes
	): Promise<AccountByteQuota | null> {
		await this.db.ready;
		const row = await this.accountByteQuota(this.relay, accountId);
		if (!row) return null;
		return {
			maxBytes: row.maxBytes ?? defaultMaxAccountBytes,
			overridden: row.maxBytes !== null
		};
	}

	private async accountByteQuota(
		client: Client | Transaction,
		accountId: string
	): Promise<{ maxBytes: number | null } | undefined> {
		const result = await client.execute({
			sql: `SELECT quotas.max_bytes AS maxBytes
				 FROM accounts
				 LEFT JOIN account_quotas AS quotas USING(account_id)
				 WHERE account_id = ?`,
			args: [accountId]
		});
		return result.rows[0] as unknown as { maxBytes: number | null } | undefined;
	}

	async setAccountByteQuota(accountId: string, maxBytes: number): Promise<boolean> {
		if (!Number.isSafeInteger(maxBytes) || maxBytes <= 0) {
			throw new RangeError('Account byte quota must be a positive safe integer');
		}
		await this.db.ready;
		const result = await this.relay.execute({
			sql: `INSERT INTO account_quotas(account_id, max_bytes)
				 SELECT account_id, ? FROM accounts WHERE account_id = ?
				 ON CONFLICT(account_id) DO UPDATE SET max_bytes = excluded.max_bytes`,
			args: [maxBytes, accountId]
		});
		return result.rowsAffected === 1;
	}

	async clearAccountByteQuota(accountId: string): Promise<boolean> {
		if (!(await this.getAuthCredential(accountId))) return false;
		await this.relay.execute({
			sql: 'DELETE FROM account_quotas WHERE account_id = ?',
			args: [accountId]
		});
		return true;
	}

	/** One page of accounts with their effective limits, newest-largest first, so
	 * the operator view opens on whatever is consuming the most. */
	async listAccounts(
		options: {
			limit?: number;
			offset?: number;
			search?: string;
			/** Exactly this account, where `search` is a prefix match. */
			accountId?: string;
			defaultMaxAccountBytes?: number;
			defaultSyncPerMinute?: number;
		} = {}
	): Promise<AccountPage> {
		await this.db.ready;
		const limit = Math.min(Math.max(Math.trunc(options.limit ?? 50), 1), 200);
		const offset = Math.max(Math.trunc(options.offset ?? 0), 0);
		const search = (options.search ?? '').trim();
		const where = options.accountId
			? 'WHERE a.account_id = ?'
			: search
				? "WHERE a.account_id LIKE ? ESCAPE '\\'"
				: '';
		const filter = options.accountId
			? [options.accountId]
			: search
				? [`${search.replace(/[\\%_]/g, '\\$&')}%`]
				: [];
		const total = (
			await this.relay.execute({
				sql: `SELECT COUNT(*) AS total FROM accounts a ${where}`,
				args: filter
			})
		).rows[0] as unknown as { total: number };
		const rows = (
			await this.relay.execute({
				sql: `SELECT a.account_id AS accountId, a.envelope_count AS envelopeCount,
						a.ciphertext_bytes AS ciphertextBytes, a.last_seen_at AS lastSeenAt,
						q.max_bytes AS maxBytes, r.sync_per_minute AS syncPerMinute,
						h.versions AS historyVersions, h.bytes AS historyBytes
					FROM accounts a
					LEFT JOIN account_quotas q ON q.account_id = a.account_id
					LEFT JOIN account_rate_limits r ON r.account_id = a.account_id
					LEFT JOIN account_history_usage h ON h.account_id = a.account_id
					${where}
					ORDER BY a.ciphertext_bytes DESC, a.account_id ASC
					LIMIT ? OFFSET ?`,
				args: [...filter, limit, offset]
			})
		).rows as unknown as Array<Record<string, number | string | null>>;
		return {
			total: Number(total.total),
			accounts: rows.map((row) =>
				this.toSummary(
					row,
					options.defaultMaxAccountBytes ?? this.maxAccountBytes,
					options.defaultSyncPerMinute ?? DEFAULT_SYNC_PER_MINUTE
				)
			)
		};
	}

	private toSummary(
		row: Record<string, number | string | null>,
		defaultMaxAccountBytes: number,
		defaultSyncPerMinute: number
	): AccountSummary {
		const envelopeCount = Number(row.envelopeCount ?? 0);
		const ciphertextBytes = Number(row.ciphertextBytes ?? 0);
		return {
			accountId: String(row.accountId),
			envelopeCount,
			ciphertextBytes,
			storageBytes:
				ciphertextBytes +
				envelopeCount * ENVELOPE_STORAGE_OVERHEAD_BYTES +
				Number(row.historyBytes ?? 0) +
				Number(row.historyVersions ?? 0) * ENVELOPE_STORAGE_OVERHEAD_BYTES,
			lastSeenAt: Number(row.lastSeenAt ?? 0),
			maxBytes: row.maxBytes == null ? defaultMaxAccountBytes : Number(row.maxBytes),
			maxBytesOverridden: row.maxBytes != null,
			syncPerMinute: row.syncPerMinute == null ? defaultSyncPerMinute : Number(row.syncPerMinute),
			syncPerMinuteOverridden: row.syncPerMinute != null
		};
	}

	/** Null when this account runs on the shared default. */
	async accountRateLimit(accountId: string): Promise<number | null> {
		await this.db.ready;
		const row = (
			await this.relay.execute({
				sql: 'SELECT sync_per_minute AS syncPerMinute FROM account_rate_limits WHERE account_id = ?',
				args: [accountId]
			})
		).rows[0] as unknown as { syncPerMinute: number } | undefined;
		return row ? Number(row.syncPerMinute) : null;
	}

	async setAccountRateLimit(accountId: string, syncPerMinute: number): Promise<boolean> {
		if (!Number.isSafeInteger(syncPerMinute) || syncPerMinute <= 0) {
			throw new RangeError('Sync rate limit must be a positive safe integer');
		}
		await this.db.ready;
		const result = await this.relay.execute({
			sql: `INSERT INTO account_rate_limits(account_id, sync_per_minute, updated_at)
				 SELECT account_id, ?, ? FROM accounts WHERE account_id = ?
				 ON CONFLICT(account_id) DO UPDATE SET
					sync_per_minute = excluded.sync_per_minute, updated_at = excluded.updated_at`,
			args: [syncPerMinute, Date.now(), accountId]
		});
		return result.rowsAffected === 1;
	}

	async clearAccountRateLimit(accountId: string): Promise<boolean> {
		if (!(await this.getAuthCredential(accountId))) return false;
		await this.relay.execute({
			sql: 'DELETE FROM account_rate_limits WHERE account_id = ?',
			args: [accountId]
		});
		return true;
	}

	async sync(
		accountId: string,
		cursor: number,
		uploads: OpaqueUpload[],
		deletions: OpaqueDelete[],
		downloadLimit = 12,
		senderClientId?: string,
		defaultMaxAccountBytes = this.maxAccountBytes
	): Promise<SyncResult & { usage: UsageRow & { maxBytes: number } }> {
		await this.db.ready;
		let resetRevisionCeiling: number | null = null;
		const result = await withTxn(this.relay, async (tx) => {
			const account = (
				await tx.execute({
					sql: `
				SELECT credential_hash AS credentialHash, next_seq AS nextSeq, envelope_count AS envelopeCount,
					ciphertext_bytes AS ciphertextBytes, updated_at AS updatedAt,
					COALESCE(history.versions, 0) AS historyVersions, COALESCE(history.bytes, 0) AS historyBytes
				FROM accounts
				LEFT JOIN account_history_usage AS history USING (account_id)
				WHERE account_id = ?
			`,
					args: [accountId]
				})
			).rows[0] as unknown as
				| (AccountRow & { updatedAt: number; historyVersions: number; historyBytes: number })
				| undefined;
			if (!account) throw new Error('Sync account does not exist');
			const quotaRow = await this.accountByteQuota(tx, accountId);
			const maxAccountBytes = quotaRow?.maxBytes ?? defaultMaxAccountBytes;

			let envelopeCount = account.envelopeCount;
			let ciphertextBytes = account.ciphertextBytes;
			// Older versions share the quota with live records but never block them: when the two
			// together exceed it, the oldest versions give way.
			let historyVersions = Number(account.historyVersions);
			let historyBytes = Number(account.historyBytes);
			const storageBytes = (activeCount = envelopeCount, activeBytes = ciphertextBytes): number =>
				activeBytes + activeCount * ENVELOPE_STORAGE_OVERHEAD_BYTES;
			const historyStorageBytes = () =>
				historyBytes + historyVersions * ENVELOPE_STORAGE_OVERHEAD_BYTES;
			const usage = (): UsageRow & { maxBytes: number } => ({
				envelopeCount,
				ciphertextBytes,
				storageBytes: storageBytes() + historyStorageBytes(),
				maxBytes: maxAccountBytes
			});
			if (cursor > account.nextSeq) {
				resetRevisionCeiling = account.nextSeq;
				await this.touchVia(tx, accountId);
				return {
					cursor: 0,
					envelopes: [],
					conflicts: [],
					hasMore: false,
					reset: true,
					writesAccepted: false,
					usage: usage()
				};
			}
			const page = (
				await tx.execute({
					sql: `
				SELECT seq, id, ciphertext, slot
				FROM envelopes
				WHERE account_id = ? AND seq > ?
				ORDER BY seq ASC
				LIMIT ?
			`,
					args: [accountId, cursor, downloadLimit + 1]
				})
			).rows as unknown as EncryptedEnvelope[];
			const hasMore = page.length > downloadLimit;
			const remote = hasMore ? page.slice(0, downloadLimit) : page;
			const attemptedWrites = uploads.length > 0 || deletions.length > 0;
			if (remote.length > 0) {
				await this.touchVia(tx, accountId);
				return {
					cursor: remote.at(-1)?.seq ?? cursor,
					envelopes: remote,
					conflicts: [],
					hasMore,
					reset: false,
					writesAccepted: !attemptedWrites,
					usage: usage()
				};
			}

			const slots = [
				...new Set([...uploads.map(({ slot }) => slot), ...deletions.map(({ slot }) => slot)])
			];
			const currentBySlot = new Map<string, EncryptedEnvelope>();
			for (const slotBatch of chunk(slots)) {
				const placeholders = slotBatch.map(() => '?').join(', ');
				const rows = (
					await tx.execute({
						sql: `SELECT seq, id, ciphertext, slot FROM envelopes
						 WHERE account_id = ? AND slot IN (${placeholders})`,
						args: [accountId, ...slotBatch]
					})
				).rows as unknown as EncryptedEnvelope[];
				for (const row of rows) currentBySlot.set(row.slot, row);
			}

			const conflicts: EncryptedEnvelope[] = [];
			for (const upload of uploads) {
				const current = currentBySlot.get(upload.slot);
				if (current && current.id !== upload.id && current.id !== (upload.expectedId ?? null)) {
					conflicts.push(current);
				}
			}
			if (conflicts.length > 0) {
				await this.touchVia(tx, accountId);
				return {
					cursor: Math.max(cursor, account.nextSeq),
					envelopes: [],
					conflicts,
					hasMore: false,
					reset: false,
					writesAccepted: false,
					usage: usage()
				};
			}

			const olderBefore = await olderVersions(tx, accountId, slots);

			const knownIds = new Set<string>();
			for (const idBatch of chunk([...new Set(uploads.map(({ id }) => id))])) {
				const placeholders = idBatch.map(() => '?').join(', ');
				const rows = (
					await tx.execute({
						sql: `SELECT id FROM envelopes WHERE account_id = ? AND id IN (${placeholders})`,
						args: [accountId, ...idBatch]
					})
				).rows as unknown as Array<{ id: string }>;
				for (const row of rows) knownIds.add(row.id);
			}

			const deletionStatements: InStatement[] = [];
			const writtenAt = Math.max(Date.now(), Number(account.updatedAt) + 1);
			for (const deletion of deletions) {
				const removed = currentBySlot.get(deletion.slot);
				if (!removed || removed.id !== deletion.id) continue;
				// Deleting a record removes it and every version of it at once.
				deletionStatements.push(
					{
						sql: 'DELETE FROM envelope_history WHERE account_id = ? AND slot = ?',
						args: [accountId, deletion.slot]
					},
					{
						sql: 'DELETE FROM envelopes WHERE account_id = ? AND slot = ? AND id = ?',
						args: [accountId, deletion.slot, deletion.id]
					}
				);
				envelopeCount -= 1;
				ciphertextBytes -= removed.ciphertext.length;
				currentBySlot.delete(deletion.slot);
				knownIds.delete(removed.id);
			}
			await executeInBatches(tx, deletionStatements);

			let sequence = account.nextSeq;
			let added = false;
			const uploadStatements: InStatement[] = [];

			for (const upload of uploads) {
				if (knownIds.has(upload.id)) continue;
				if (!BASE64URL.test(upload.ciphertext)) {
					throw new Error('Envelope ciphertext is not base64url');
				}
				const prior = currentBySlot.get(upload.slot);
				const projectedCount = envelopeCount + (prior ? 0 : 1);
				const projectedBytes =
					ciphertextBytes + upload.ciphertext.length - (prior?.ciphertext.length ?? 0);
				const projectedStorageBytes = storageBytes(projectedCount, projectedBytes);
				if (projectedStorageBytes > maxAccountBytes && projectedStorageBytes >= storageBytes()) {
					throw new SyncQuotaExceededError();
				}
				sequence += 1;
				if (prior && upload.continues)
					uploadStatements.push({
						sql: 'DELETE FROM envelope_history WHERE account_id = ? AND id = ?',
						args: [accountId, prior.id]
					});
				else if (prior)
					uploadStatements.push({
						sql: `INSERT INTO envelope_history(account_id, slot, id, ciphertext, saved_at)
							SELECT ?, ?, ?, ?, ? WHERE NOT EXISTS (
								SELECT 1 FROM envelope_history WHERE account_id = ? AND id = ?
							)`,
						args: [
							accountId,
							prior.slot,
							prior.id,
							prior.ciphertext,
							writtenAt,
							accountId,
							prior.id
						]
					});
				uploadStatements.push({
					sql: `INSERT INTO envelopes(account_id, slot, seq, id, ciphertext)
					VALUES (?, ?, ?, ?, ?)
					ON CONFLICT(account_id, slot) DO UPDATE SET
						seq = excluded.seq,
						id = excluded.id,
						ciphertext = excluded.ciphertext`,
					args: [accountId, upload.slot, sequence, upload.id, upload.ciphertext]
				});
				uploadStatements.push({
					sql: `INSERT INTO envelope_history(account_id, slot, id, ciphertext, saved_at)
						VALUES (?, ?, ?, ?, ?)`,
					args: [accountId, upload.slot, upload.id, upload.ciphertext, writtenAt]
				});
				if (prior) knownIds.delete(prior.id);
				knownIds.add(upload.id);
				currentBySlot.set(upload.slot, { ...upload, seq: sequence });
				envelopeCount = projectedCount;
				ciphertextBytes = projectedBytes;
				added = true;
			}
			// Each record keeps a rolling window of its newest versions, the live one included.
			const touchedSlots = new Set([
				...uploads.map((upload) => upload.slot),
				...deletions.map((deletion) => deletion.slot)
			]);
			for (const slots of chunk([...touchedSlots]))
				uploadStatements.push({
					sql: `DELETE FROM envelope_history WHERE history_id IN (
						SELECT history_id FROM (
							SELECT history_id,
								ROW_NUMBER() OVER (PARTITION BY slot ORDER BY history_id DESC) AS position
							FROM envelope_history
							WHERE account_id = ? AND slot IN (${slots.map(() => '?').join(', ')})
						) WHERE position > ?
					)`,
					args: [accountId, ...slots, this.historyVersions]
				});
			await executeInBatches(tx, uploadStatements);

			const olderAfter = await olderVersions(tx, accountId, slots);
			historyVersions += olderAfter.versions - olderBefore.versions;
			historyBytes += olderAfter.bytes - olderBefore.bytes;
			if (storageBytes() + historyStorageBytes() > maxAccountBytes && historyVersions > 0) {
				const oldest = (
					await tx.execute({
						sql: `SELECT history_id AS historyId, length(ciphertext) AS bytes
						FROM envelope_history AS history
						WHERE account_id = ? AND ${OLDER_VERSION}
						ORDER BY history_id ASC`,
						args: [accountId]
					})
				).rows as unknown as Array<{ historyId: number; bytes: number }>;
				const evicted: number[] = [];
				for (const row of oldest) {
					if (storageBytes() + historyStorageBytes() <= maxAccountBytes) break;
					evicted.push(row.historyId);
					historyVersions -= 1;
					historyBytes -= Number(row.bytes);
				}
				await executeInBatches(
					tx,
					chunk(evicted).map((ids) => ({
						sql: `DELETE FROM envelope_history WHERE history_id IN (${ids.map(() => '?').join(', ')})`,
						args: ids
					}))
				);
			}
			if (
				historyVersions !== Number(account.historyVersions) ||
				historyBytes !== Number(account.historyBytes)
			)
				await tx.execute({
					sql: `INSERT INTO account_history_usage(account_id, versions, bytes) VALUES (?, ?, ?)
					ON CONFLICT(account_id) DO UPDATE SET versions = excluded.versions, bytes = excluded.bytes`,
					args: [accountId, historyVersions, historyBytes]
				});

			const seenAt = writtenAt;
			if (added || deletions.length > 0) {
				await tx.execute({
					sql: `
					UPDATE accounts
					SET next_seq = ?, envelope_count = ?, ciphertext_bytes = ?, updated_at = ?, last_seen_at = ?
					WHERE account_id = ?
				`,
					args: [sequence, envelopeCount, ciphertextBytes, seenAt, seenAt, accountId]
				});
			} else {
				await this.touchVia(tx, accountId, seenAt);
			}

			return {
				cursor: Math.max(cursor, sequence),
				envelopes: [],
				conflicts: [],
				hasMore: false,
				reset: false,
				writesAccepted: true,
				usage: usage()
			};
		});
		if (resetRevisionCeiling !== null) {
			await this.discardWakeSnapshotAfter(accountId, resetRevisionCeiling);
		}
		if (result.writesAccepted && (uploads.length > 0 || deletions.length > 0)) {
			syncEventEmitter.notify(accountId, result.cursor, senderClientId);
		}
		return result;
	}

	async deleteAccount(accountId: string): Promise<boolean> {
		await this.db.ready;
		const deleted = await withTxn(this.relay, async (tx) => {
			const result = await tx.execute({
				sql: 'DELETE FROM accounts WHERE account_id = ? RETURNING account_id',
				args: [accountId]
			});
			if (result.rows.length === 0) return false;
			await tx.execute({
				sql: 'INSERT OR IGNORE INTO pending_ops_deletions(account_id, queued_at) VALUES (?, ?)',
				args: [accountId, Date.now()]
			});
			return true;
		});
		await this.drainPendingOpsDeletions();
		return deleted;
	}

	private async purgeAccountOpsState(accountIds: string[]): Promise<void> {
		for (const ids of chunk(accountIds)) {
			const placeholders = ids.map(() => '?').join(', ');
			await this.ops.batch(
				[
					{
						sql: `DELETE FROM reminder_push_devices WHERE account_id IN (${placeholders})`,
						args: ids
					},
					{
						sql: `DELETE FROM reminder_wakes WHERE account_id IN (${placeholders})`,
						args: ids
					},
					{
						sql: `DELETE FROM reminder_wake_revisions WHERE account_id IN (${placeholders})`,
						args: ids
					},
					{
						sql: `DELETE FROM reminder_wake_deliveries WHERE account_id IN (${placeholders})`,
						args: ids
					}
				],
				'write'
			);
		}
	}

	private async drainPendingOpsDeletions(): Promise<void> {
		const pending = (
			await this.relay.execute('SELECT account_id AS accountId FROM pending_ops_deletions')
		).rows as unknown as Array<{ accountId: string }>;
		for (const rows of chunk(pending)) {
			const accountIds = rows.map(({ accountId }) => accountId);
			await this.purgeAccountOpsState(accountIds);
			const placeholders = accountIds.map(() => '?').join(', ');
			await this.relay.execute({
				sql: `DELETE FROM pending_ops_deletions WHERE account_id IN (${placeholders})`,
				args: accountIds
			});
		}
	}

	private async discardWakeSnapshotAfter(accountId: string, revision: number): Promise<void> {
		await withTxn(this.ops, async (tx) => {
			const stale = (
				await tx.execute({
					sql: 'SELECT 1 AS present FROM reminder_wake_revisions WHERE account_id = ? AND revision > ?',
					args: [accountId, revision]
				})
			).rows[0];
			if (!stale) return;
			await tx.batch([
				{ sql: 'DELETE FROM reminder_wakes WHERE account_id = ?', args: [accountId] },
				{
					sql: 'DELETE FROM reminder_wake_revisions WHERE account_id = ? AND revision > ?',
					args: [accountId, revision]
				}
			]);
		});
	}

	async touchAccount(accountId: string, now = Date.now()): Promise<void> {
		await this.db.ready;
		await this.touchVia(this.relay, accountId, now);
	}

	private async touchVia(
		client: Client | Transaction,
		accountId: string,
		now = Date.now()
	): Promise<void> {
		await client.execute({
			sql: 'UPDATE accounts SET last_seen_at = ? WHERE account_id = ?',
			args: [now, accountId]
		});
	}

	getQuotas(maxAccountBytes = this.maxAccountBytes): SyncQuotas {
		return {
			maxAccountBytes
		};
	}

	async operatorUsage(
		options: {
			now?: number;
			staleBefore?: number | null;
		} = {}
	): Promise<OperatorUsage> {
		await this.db.ready;
		const now = options.now ?? Date.now();
		const windows = ACTIVITY_WINDOWS_DAYS;
		const staleBefore = options.staleBefore ?? null;
		const activeSelects = windows
			.map(
				(_, index) =>
					`COALESCE(SUM(CASE WHEN last_seen_at >= ? THEN 1 ELSE 0 END), 0) AS active_${index}`
			)
			.join(',\n');
		const sql = `
			SELECT
				COUNT(*) AS accounts,
				COALESCE(SUM(envelope_count), 0) AS envelopeCount,
				COALESCE(SUM(ciphertext_bytes), 0) AS ciphertextBytes,
				(SELECT COALESCE(SUM(bytes + versions * ${ENVELOPE_STORAGE_OVERHEAD_BYTES}), 0)
					FROM account_history_usage) AS historyStorageBytes,
				${activeSelects ? `${activeSelects},` : ''}
				COALESCE(SUM(CASE WHEN last_seen_at < ? THEN 1 ELSE 0 END), 0) AS staleAccounts
			FROM accounts
		`;
		const row = (
			await this.relay.execute({
				sql,
				args: [...windows.map((days) => now - days * 24 * 60 * 60 * 1000), staleBefore ?? 0]
			})
		).rows[0] as Record<string, number>;
		const activeByWindowDays: Record<string, number> = {};
		for (const [index, days] of windows.entries()) {
			activeByWindowDays[String(days)] = row[`active_${index}`] ?? 0;
		}
		return {
			accounts: row.accounts,
			envelopeCount: row.envelopeCount,
			ciphertextBytes: row.ciphertextBytes,
			storageBytes:
				row.ciphertextBytes +
				row.envelopeCount * ENVELOPE_STORAGE_OVERHEAD_BYTES +
				Number(row.historyStorageBytes),
			activeByWindowDays,
			staleAccounts: staleBefore == null ? 0 : row.staleAccounts
		};
	}

	async deleteInactiveAccounts(staleBefore: number): Promise<number> {
		await this.db.ready;
		const deleted = await withTxn(this.relay, async (tx) => {
			const rows = (
				await tx.execute({
					sql: 'DELETE FROM accounts WHERE last_seen_at < ? RETURNING account_id AS accountId',
					args: [staleBefore]
				})
			).rows as unknown as Array<{ accountId: string }>;
			await executeInBatches(
				tx,
				rows.map(({ accountId }) => ({
					sql: 'INSERT OR IGNORE INTO pending_ops_deletions(account_id, queued_at) VALUES (?, ?)',
					args: [accountId, Date.now()]
				}))
			);
			return rows;
		});
		await this.drainPendingOpsDeletions();
		return deleted.length;
	}

	/**
	 * Daily storage upkeep. Deletes already remove a record and its versions at once, so this
	 * only enforces the version window everywhere (it may have been lowered) and recounts
	 * history usage from the rows.
	 */
	// `now` keeps the shared store surface; nothing here waits on time.
	async reclaimStorage(_now?: number): Promise<number> {
		await this.db.ready;
		return withTxn(this.relay, async (tx) => {
			const pruned = await tx.execute({
				sql: `DELETE FROM envelope_history WHERE history_id IN (
					SELECT history_id FROM (
						SELECT history_id, ROW_NUMBER() OVER (
							PARTITION BY account_id, slot ORDER BY history_id DESC
						) AS position
						FROM envelope_history
					) WHERE position > ?
				)`,
				args: [this.historyVersions]
			});
			await tx.batch([
				'DELETE FROM account_history_usage',
				`INSERT INTO account_history_usage(account_id, versions, bytes)
				SELECT account_id, COUNT(*), SUM(length(ciphertext)) FROM envelope_history AS history
				WHERE ${OLDER_VERSION} GROUP BY account_id`
			]);
			return pruned.rowsAffected;
		});
	}

	/** Register one account-scoped browser endpoint without changing account wakes. */
	async savePushDevice(device: PushDeviceInput): Promise<void> {
		await this.db.ready;
		await withTxn(this.ops, async (tx) => {
			const existing = (
				await tx.execute({
					sql: 'SELECT 1 AS present FROM reminder_push_devices WHERE account_id = ? AND device_id = ?',
					args: [device.accountId, device.deviceId]
				})
			).rows[0];

			await tx.execute({
				sql: 'DELETE FROM reminder_push_devices WHERE endpoint = ? AND (account_id != ? OR device_id != ?)',
				args: [device.endpoint, device.accountId, device.deviceId]
			});
			await tx.execute({
				sql: 'DELETE FROM reminder_push_devices WHERE device_id = ? AND account_id != ?',
				args: [device.deviceId, device.accountId]
			});

			if (!existing) {
				const extras = (
					await tx.execute({
						sql: 'SELECT device_id AS deviceId FROM reminder_push_devices WHERE account_id = ? ORDER BY updated_at ASC',
						args: [device.accountId]
					})
				).rows as unknown as Array<{ deviceId: string }>;
				const overflow = extras.length + 1 - MAX_PUSH_DEVICES;
				if (overflow > 0) {
					for (const row of extras.slice(0, overflow)) {
						await tx.execute({
							sql: 'DELETE FROM reminder_push_devices WHERE account_id = ? AND device_id = ?',
							args: [device.accountId, row.deviceId]
						});
					}
				}
			}

			await tx.execute({
				sql: `
				INSERT INTO reminder_push_devices(
					account_id, device_id, endpoint, p256dh, auth, updated_at
				)
				VALUES (?, ?, ?, ?, ?, ?)
				ON CONFLICT(account_id, device_id) DO UPDATE SET
					endpoint = excluded.endpoint,
					p256dh = excluded.p256dh,
					auth = excluded.auth,
					updated_at = excluded.updated_at
			`,
				args: [
					device.accountId,
					device.deviceId,
					device.endpoint,
					device.p256dh,
					device.auth,
					Date.now()
				]
			});
		});
		await this.touchAccount(device.accountId);
	}

	async replaceReminderWakes(
		accountId: string,
		wakes: ReminderWakeInput[],
		revision?: number
	): Promise<boolean> {
		await this.db.ready;
		const account = (
			await this.relay.execute({
				sql: 'SELECT 1 AS present FROM accounts WHERE account_id = ?',
				args: [accountId]
			})
		).rows[0];
		if (!account) return false;
		const limitedWakes = wakes.slice(0, MAX_WAKES_PER_ACCOUNT);
		const accepted = await withTxn(this.ops, async (tx) => {
			if (revision !== undefined) {
				const currentRevision = (
					await tx.execute({
						sql: 'SELECT revision FROM reminder_wake_revisions WHERE account_id = ?',
						args: [accountId]
					})
				).rows[0] as unknown as { revision: number } | undefined;
				if (currentRevision && revision < currentRevision.revision) return false;
				if (currentRevision?.revision === revision) {
					const current = (
						await tx.execute({
							sql: `SELECT wake_id AS id, fire_at AS fireAt FROM reminder_wakes
							 WHERE account_id = ? ORDER BY wake_id ASC, fire_at ASC`,
							args: [accountId]
						})
					).rows as unknown as ReminderWakeInput[];
					const expected = [...limitedWakes].sort((left, right) =>
						left.id < right.id ? -1 : left.id > right.id ? 1 : left.fireAt - right.fireAt
					);
					return JSON.stringify(current) === JSON.stringify(expected);
				}
			}
			await tx.execute({
				sql: 'DELETE FROM reminder_wakes WHERE account_id = ?',
				args: [accountId]
			});
			const statements: InStatement[] = limitedWakes.map((wake) => ({
				sql: 'INSERT INTO reminder_wakes(account_id, wake_id, fire_at) VALUES (?, ?, ?)',
				args: [accountId, wake.id, wake.fireAt]
			}));
			if (revision !== undefined) {
				statements.push({
					sql: `INSERT INTO reminder_wake_revisions(account_id, revision) VALUES (?, ?)
						ON CONFLICT(account_id) DO UPDATE SET revision = excluded.revision`,
					args: [accountId, revision]
				});
			}
			await executeInBatches(tx, statements);
			return true;
		});
		if (accepted) await this.touchAccount(accountId);
		return accepted;
	}

	async claimDueWakes(now: number, limit = 100): Promise<DueWake[]> {
		await this.db.ready;
		return withTxn(this.ops, async (tx) => {
			const rows = (
				await tx.execute({
					sql: `SELECT
					d.account_id AS accountId,
					d.device_id AS deviceId,
					w.wake_id AS wakeId,
					w.fire_at AS fireAt,
					d.endpoint AS endpoint,
					d.p256dh AS p256dh,
					d.auth AS auth
				 FROM reminder_wakes w
				 INNER JOIN reminder_push_devices d ON d.account_id = w.account_id
				 LEFT JOIN reminder_wake_deliveries x
					ON x.account_id = d.account_id
					AND x.device_id = d.device_id
					AND x.wake_id = w.wake_id
				 WHERE w.fire_at <= ?
					AND x.delivered_at IS NULL
					AND (x.claimed_at IS NULL OR x.claimed_at <= ?)
				 ORDER BY w.fire_at ASC, w.wake_id ASC, d.device_id ASC
				 LIMIT ?`,
					args: [now, now - WAKE_CLAIM_LEASE_MS, limit]
				})
			).rows as unknown as DueWake[];
			for (const row of rows) {
				await tx.execute({
					sql: `INSERT INTO reminder_wake_deliveries(
					account_id, device_id, wake_id, claimed_at, delivered_at
				 ) VALUES (?, ?, ?, ?, NULL)
				 ON CONFLICT(account_id, device_id, wake_id) DO UPDATE SET
					claimed_at = excluded.claimed_at,
					delivered_at = NULL`,
					args: [row.accountId, row.deviceId, row.wakeId, now]
				});
			}
			return rows;
		});
	}

	async markWakeDelivered(
		wake: Pick<DueWake, 'accountId' | 'deviceId' | 'wakeId'>,
		now: number
	): Promise<void> {
		await this.db.ready;
		await this.ops.execute({
			sql: `UPDATE reminder_wake_deliveries SET delivered_at = ?
			 WHERE account_id = ? AND device_id = ? AND wake_id = ?`,
			args: [now, wake.accountId, wake.deviceId, wake.wakeId]
		});
	}

	async releaseWakeClaim(wake: Pick<DueWake, 'accountId' | 'deviceId' | 'wakeId'>): Promise<void> {
		await this.db.ready;
		await this.ops.execute({
			sql: `DELETE FROM reminder_wake_deliveries
			 WHERE account_id = ? AND device_id = ? AND wake_id = ? AND delivered_at IS NULL`,
			args: [wake.accountId, wake.deviceId, wake.wakeId]
		});
	}

	async pruneStaleWakes(now: number, retainMs = WAKE_RETAIN_MS): Promise<void> {
		await this.db.ready;
		const cutoff = now - retainMs;
		await withTxn(this.ops, async (tx) => {
			await tx.execute({ sql: 'DELETE FROM reminder_wakes WHERE fire_at < ?', args: [cutoff] });
			await tx.execute({
				sql: `DELETE FROM reminder_wake_deliveries
				 WHERE COALESCE(delivered_at, claimed_at) < ?`,
				args: [cutoff]
			});
		});
	}

	async deletePushDevice(accountId: string, deviceId: string): Promise<void> {
		await this.db.ready;
		await this.ops.execute({
			sql: 'DELETE FROM reminder_push_devices WHERE account_id = ? AND device_id = ?',
			args: [accountId, deviceId]
		});
		await this.touchAccount(accountId);
	}

	async countPushDevices(accountId?: string): Promise<number> {
		await this.db.ready;
		const result = accountId
			? await this.ops.execute({
					sql: 'SELECT COUNT(*) AS count FROM reminder_push_devices WHERE account_id = ?',
					args: [accountId]
				})
			: await this.ops.execute('SELECT COUNT(*) AS count FROM reminder_push_devices');
		return (result.rows[0] as unknown as { count: number }).count;
	}

	async isReady(): Promise<boolean> {
		try {
			await this.db.ready;
			await this.relay.execute('SELECT 1 AS ready');
			await this.ops.execute('SELECT 1 AS ready');
			return true;
		} catch {
			return false;
		}
	}

	// Async so both deployments expose the same shape; see
	// syncStore.contract.test.ts. The Cloudflare store has to await its
	// coordinator before it can hand back a stream.
	async createEventStream(
		accountId: string,
		signal?: AbortSignal,
		clientId?: string
	): Promise<Response> {
		const encoder = new TextEncoder();
		let unsubscribe: (() => void) | undefined;
		let pingInterval: ReturnType<typeof setInterval> | undefined;

		const stream = new ReadableStream({
			start(controller) {
				try {
					controller.enqueue(encoder.encode(': ok\n\n'));
				} catch {
					return;
				}
				unsubscribe = syncEventEmitter.subscribe(accountId, (seq, senderClientId) => {
					if (clientId && senderClientId && clientId === senderClientId) return;
					try {
						controller.enqueue(encoder.encode(`data: ${JSON.stringify({ seq })}\n\n`));
					} catch {
						/* stream closed */
					}
				});
				pingInterval = setInterval(() => {
					try {
						controller.enqueue(encoder.encode(': ping\n\n'));
					} catch {
						/* stream closed */
					}
				}, 25_000);
			},
			cancel() {
				if (pingInterval) clearInterval(pingInterval);
				if (unsubscribe) unsubscribe();
			}
		});

		signal?.addEventListener('abort', () => {
			if (pingInterval) clearInterval(pingInterval);
			if (unsubscribe) unsubscribe();
		});

		return new Response(stream, {
			headers: {
				'Content-Type': 'text/event-stream',
				'Cache-Control': 'no-cache, no-transform',
				Connection: 'keep-alive'
			}
		});
	}
}

let singleton: SyncStore | undefined;

export function getSyncStore(): SyncStore {
	singleton ??= new SyncStore(getDb(), {
		maxAccountBytes: parseMaxAccountBytes(env.SCRAPSCACHE_SYNC_MAX_ACCOUNT_BYTES),
		historyVersions: parseHistoryVersions(env.SCRAPSCACHE_HISTORY_VERSIONS)
	});
	return singleton;
}
