// Generated by @sveltejs/adapter-cloudflare during `npm run build:cloudflare`.
// @ts-expect-error generated build entry has no source declaration
import app from '../.svelte-kit/cloudflare/_worker.js';
import type { ExecutionContext, ExportedHandler, MessageBatch } from '@cloudflare/workers-types';

export { AccountCoordinator } from './accountCoordinator';

type Env = { SCRAPSCACHE_TICK_SECRET?: string };

/** One account's due reminder wakes, delivered by the app's own route in this isolate. */
async function deliverAccount(
	accountId: string,
	env: Env,
	context: ExecutionContext
): Promise<boolean> {
	const response: Response = await app.fetch(
		new Request('https://scrapscache.internal/api/cron/wakes', {
			method: 'POST',
			headers: {
				authorization: `Bearer ${env.SCRAPSCACHE_TICK_SECRET ?? ''}`,
				'content-type': 'application/json'
			},
			body: JSON.stringify({ accountId })
		}),
		env,
		context
	);
	return response.ok;
}

/**
 * The generated adapter checks the shared Worker cache before it runs hooks.
 * A stale HTML shell can therefore be returned before hooks can mark it
 * private. Bypass that lookup for browser navigations; hashed assets retain
 * the generated cache behaviour.
 */
const worker: ExportedHandler<Env> = {
	fetch(request, env, context) {
		const acceptsHtml = request.headers.get('accept')?.toLowerCase().includes('text/html');
		if (request.method === 'GET' && acceptsHtml) {
			const headers = new Headers(request.headers);
			headers.set('cache-control', 'no-cache');
			request = new Request(request, { headers });
		}
		return app.fetch(request, env, context);
	},

	/** Accounts whose reminder alarm fired, from the reminders Worker's wake queue. */
	async queue(batch: MessageBatch<unknown>, env, context) {
		await Promise.all(
			batch.messages.map(async (message) => {
				const accountId = (message.body as { accountId?: unknown } | null)?.accountId;
				if (typeof accountId !== 'string') {
					message.ack();
					return;
				}
				const delivered = await deliverAccount(accountId, env, context).catch(() => false);
				if (delivered) message.ack();
				else message.retry();
			})
		);
	}
};

export default worker;
