// Generated by @sveltejs/adapter-cloudflare during `npm run build:cloudflare`.
// @ts-expect-error generated build entry has no source declaration
import app from '../.svelte-kit/cloudflare/_worker.js';
import type { ExportedHandler } from '@cloudflare/workers-types';

export { AccountCoordinator } from './accountCoordinator';

/**
 * The generated adapter checks the shared Worker cache before it runs hooks.
 * A stale HTML shell can therefore be returned before hooks can mark it
 * private. Bypass that lookup for browser navigations; hashed assets retain
 * the generated cache behaviour.
 */
const worker: ExportedHandler = {
	fetch(request, env, context) {
		const acceptsHtml = request.headers.get('accept')?.toLowerCase().includes('text/html');
		if (request.method === 'GET' && acceptsHtml) {
			const headers = new Headers(request.headers);
			headers.set('cache-control', 'no-cache');
			request = new Request(request, { headers });
		}
		return app.fetch(request, env, context);
	}
};

export default worker;
