// Generated by @sveltejs/adapter-cloudflare during `npm run build:cloudflare`.
// @ts-expect-error generated build entry has no source declaration
import app from '../.svelte-kit/cloudflare/_worker.js';
import { stampOriginlessOAuthToken } from '../src/lib/server/mcp/oauthCsrf';

export { AccountCoordinator } from './accountCoordinator';
export { AccountMcpSession } from './accountMcpSession';

export default {
	fetch(request: Request, env: unknown, ctx: unknown) {
		return app.fetch(stampOriginlessOAuthToken(request), env, ctx);
	}
};
